# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCourses', '0002_course_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course',
            new_name='name',
        ),
    ]
